# Generated by Django 6.0.4 on 2026-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_alter_review_options_remove_property_max_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
